# Generated by Django 2.2.10 on 2020-09-22 21:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0007_auto_20200904_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='city',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='donor',
            name='country',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='donor',
            name='first_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='donor',
            name='home_phone',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='donor',
            name='last_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='donor',
            name='state',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='donor',
            name='street1',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='donor',
            name='street2',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='donor',
            name='zip',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='phototag',
            name='creator',
            field=models.ManyToManyField(editable=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
