# Generated by Django 2.2.10 on 2020-10-01 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0008_auto_20200922_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donor',
            options={'ordering': ('last_name', 'first_name')},
        ),
    ]
