# Generated by Django 2.2.10 on 2020-12-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0011_auto_20201029_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCutoff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
    ]
