# Generated by Django 2.2.10 on 2021-03-26 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0016_auto_20210115_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='archive.Donor'),
        ),
    ]
