# Generated by Django 2.2.10 on 2021-03-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0017_auto_20210326_2103'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.CheckConstraint(check=models.Q(('is_published', False), ('donor__isnull', False), _connector='OR'), name='never_published_without_donor'),
        ),
    ]
