# Generated by Django 2.2.10 on 2021-03-31 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0019_auto_20210331_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='photo',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='county',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='photo',
            name='state',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
