# Generated by Django 2.2.10 on 2021-09-23 20:08

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0023_auto_20210407_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='location_bounds',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='photo',
            name='location_point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
