# Generated by Django 3.2.8 on 2022-06-21 02:59

from django.db import migrations
from django.db.models import F

def copy_address(apps, schema_editor):
    CSVRecord = apps.get_model('archive', 'CSVRecord')
    Photo = apps.get_model('archive', 'Photo')
    for photo in Photo.objects.filter(csvrecord__isnull=False).exclude(csvrecord__address=''):
        photo.address = photo.csvrecord.address
        photo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0026_auto_20220621_0257'),
    ]

    operations = [
        migrations.RunPython(copy_address)
    ]
