# Generated by Django 3.2.15 on 2023-01-22 21:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0035_photo_local_context_id_squashed_0037_alter_photo_local_context_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='year',
            field=models.SmallIntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=1800), django.core.validators.MaxValueValidator(limit_value=2023)]),
        ),
    ]
