# Generated by Django 3.2.17 on 2023-02-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0039_auto_20230209_0624'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='photospherepair',
            index=models.Index(fields=['photo', 'photosphere'], name='archive_pho_photo_i_2810c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='photospherepair',
            constraint=models.UniqueConstraint(fields=('photo', 'photosphere'), name='unique_photosphere_photo'),
        ),
    ]
