# Generated by Django 3.2.17 on 2023-02-16 07:19

from django.db import migrations

def create_default_archive(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Archive = apps.get_model('kronofoto', 'Archive')
    Archive.objects.using(db_alias).create(
        name='Default',
        short_name='default',
        cms_root='',
        slug='default',
    )

def backwards(*args, **kwargs):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0041_archive'),
    ]

    operations = [
        migrations.RunPython(create_default_archive, backwards),
    ]
