# Generated by Django 3.2.17 on 2023-02-16 07:25

from django.db import migrations

def set_default_archive(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Archive = apps.get_model('archive', 'Archive')
    archive = Archive.objects.using(db_alias).get(slug='default')
    Donor = apps.get_model('archive', 'Donor')
    Donor.objects.update(kronofoto.archive)
    Photo = apps.get_model('archive', 'Photo')
    Photo.objects.update(kronofoto.archive)


def backwards(*args, **kwargs):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0043_auto_20230216_0725'),
    ]

    operations = [
        migrations.RunPython(set_default_archive, backwards),
    ]
