# Generated by Django 3.2.17 on 2023-02-16 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0045_auto_20230216_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
