# Generated by Django 3.2.17 on 2023-02-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0047_alter_archive_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='short_name',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
