# Generated by Django 3.2.17 on 2023-02-27 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0048_auto_20230216_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='short_name',
        ),
    ]
