# Generated by Django 3.2.17 on 2023-02-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0049_remove_archive_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
