# Generated by Django 3.2.17 on 2023-03-09 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0050_alter_archive_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnecticutRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id1', models.IntegerField()),
                ('file_id2', models.IntegerField()),
                ('title', models.TextField()),
                ('contributor', models.TextField()),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('photo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kronofoto.photo')),
            ],
        ),
        migrations.AddIndex(
            model_name='connecticutrecord',
            index=models.Index(fields=['file_id1', 'file_id2'], name='kronofoto_c_file_id_3e40fb_idx'),
        ),
        migrations.AddConstraint(
            model_name='connecticutrecord',
            constraint=models.UniqueConstraint(fields=('file_id1', 'file_id2'), name='unique_id_combo'),
        ),
    ]
