# Generated by Django 3.2.21 on 2023-09-12 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0060_auto_20230907_0517'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainStreetSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='photosphere',
            name='links',
            field=models.ManyToManyField(related_name='_kronofoto.photosphere_links_+', to='archive.PhotoSphere'),
        ),
        migrations.AddField(
            model_name='photosphere',
            name='mainstreetset',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kronofoto.mainstreetset'),
        ),
    ]
