# Generated by Django 3.2.21 on 2023-09-14 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0062_donor_users_starred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photographer_temp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kronofoto.photo_photographed', to='kronofoto.donor'),
        ),
        migrations.AddField(
            model_name='submission',
            name='photographer_temp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archive_submission_photographed', to='kronofoto.donor'),
        ),
    ]
