# Generated by Django 3.2.21 on 2023-09-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0067_auto_20230914_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='is_contributor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donor',
            name='is_photographer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donor',
            name='is_scanner',
            field=models.BooleanField(default=False),
        ),
    ]
