# Generated by Django 3.2.21 on 2023-09-14 06:29

from django.db import migrations
from django.db.models import Count, QuerySet

def set_contribution_flags(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Donor = apps.get_model('archive', 'Donor')
    donors = list(Donor.objects.annotate(count=Count('photo')).filter(count__gte=1))
    for donor in donors:
        donor.is_contributor = True
    Donor.objects.bulk_update(donors, ['is_contributor'])

    donors = list(Donor.objects.annotate(count=Count('kronofoto.photo_scanned')).filter(count__gte=1))
    for donor in donors:
        donor.is_scanner = True
    Donor.objects.bulk_update(donors, ['is_scanner'])

    donors = list(Donor.objects.annotate(count=Count('kronofoto.photo_photographed')).filter(count__gte=1))
    for donor in donors:
        donor.is_photographer = True
    Donor.objects.bulk_update(donors, ['is_photographer'])


def backwards(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0068_auto_20230914_0628'),
    ]

    operations = [
        migrations.RunPython(set_contribution_flags, backwards)
    ]
