# Generated by Django 3.2.21 on 2023-09-14 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0069_auto_20230914_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='donor',
            field=models.ForeignKey(limit_choices_to={'is_contributor': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='kronofoto.donor'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photographer',
            field=models.ForeignKey(limit_choices_to={'is_photographer': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kronofoto.photo_photographed', to='kronofoto.donor'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='scanner',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_scanner': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kronofoto.photo_scanned', to='kronofoto.donor'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='donor',
            field=models.ForeignKey(limit_choices_to={'is_contributor': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='kronofoto.donor'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='photographer',
            field=models.ForeignKey(limit_choices_to={'is_photographer': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archive_submission_photographed', to='kronofoto.donor'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='scanner',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_scanner': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_submission_scanned', to='kronofoto.donor'),
        ),
    ]
