# Generated by Django 3.2.21 on 2023-09-18 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0070_auto_20230914_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kronofoto.donor'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photographer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kronofoto.photo_photographed', to='kronofoto.donor'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='scanner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kronofoto.photo_scanned', to='kronofoto.donor'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kronofoto.donor'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='photographer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archive_submission_photographed', to='kronofoto.donor'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='scanner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_submission_scanned', to='kronofoto.donor'),
        ),
    ]
