# Generated by Django 3.2.21 on 2023-10-13 04:41

from django.db import migrations

def create_photo_category(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Category = apps.get_model('kronofoto', 'Category')
    Term = apps.get_model('kronofoto', 'Term')
    Photo = apps.get_model('kronofoto', 'Photo')
    Submission = apps.get_model('kronofoto', 'Submission')
    Archive = apps.get_model('kronofoto', 'Archive')
    ValidCategory = apps.get_model('kronofoto', 'ValidCategory')
    photos_category = Category.objects.using(db_alias).create(
        name='Photos',
        slug='photos',
    )
    for archive in Archive.objects.all():
        archive.categories.add(photos_category)
        vc = ValidCategory.objects.get(archive=archive, category=photos_category)
        vc.terms.set(Term.objects.all())

    Photo.objects.update(category=photos_category)
    Submission.objects.update(category=photos_category)

def backwards(*args, **kwargs):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0077_auto_20231013_0437'),
    ]

    operations = [
        migrations.RunPython(create_photo_category, backwards),
    ]
