# Generated by Django 3.2.21 on 2023-10-13 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0078_auto_20231013_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kronofoto.category'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kronofoto.category'),
        ),
    ]
