# Generated by Django 3.2.22 on 2023-11-28 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0084_auto_20231128_0007'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wordcount',
            unique_together={('word', 'field', 'photo')},
        ),
        migrations.AlterIndexTogether(
            name='wordcount',
            index_together={('word', 'field', 'photo')},
        ),
    ]
