# Generated by Django 3.2.22 on 2023-12-10 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0085_auto_20231128_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='term',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kronofoto_term_terms', to='kronofoto.termgroup'),
        ),
    ]
