# Generated by Django 3.2.22 on 2023-12-11 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0086_auto_20231210_0643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='is_contributor',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='is_photographer',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='is_scanner',
        ),
    ]
