# Generated by Django 3.2.22 on 2023-12-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0088_place_placetype'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['name'], name='kronofoto_p_name_290a32_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['place_type', 'name', 'parent'], name='kronofoto_p_place_t_ede793_idx'),
        ),
        migrations.AddIndex(
            model_name='placetype',
            index=models.Index(fields=['name'], name='kronofoto_p_name_c31844_idx'),
        ),
    ]
