# Generated by Django 3.2.22 on 2024-01-03 23:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0093_auto_20231223_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='year',
            field=models.SmallIntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=1800), django.core.validators.MaxValueValidator(limit_value=2024)]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='year',
            field=models.SmallIntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=1800), django.core.validators.MaxValueValidator(limit_value=2024)]),
        ),
    ]
