# Generated by Django 4.2.9 on 2024-01-11 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0097_alter_photo_photographer_alter_photo_place_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='donor',
            new_name='kronofoto_d_last_na_8b87fd_idx',
            old_fields=('last_name', 'first_name'),
        ),
        migrations.RenameIndex(
            model_name='photo',
            new_name='archive_pho_year_f1f0b8_idx',
            old_fields=('year', 'is_published'),
        ),
        migrations.AlterIndexTogether(
            name='wordcount',
            index_together=set(),
        ),
    ]
