# Generated by Django 4.2.9 on 2024-02-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kronofoto", "0104_place_place_icase_fullname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="address",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="photo",
            name="city",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="photo",
            name="country",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="photo",
            name="county",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="photo",
            name="state",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="submission",
            name="address",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="submission",
            name="city",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="submission",
            name="country",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="county",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="submission",
            name="state",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name="archive",
            index=models.Index(fields=["slug"], name="archive_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                condition=models.Q(("is_published", True), ("year__isnull", False)),
                fields=["donor_id", "year", "id"],
                name="donor_year_id_sort",
            ),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                condition=models.Q(("is_published", True), ("year__isnull", False)),
                fields=["donor_id", "category", "year", "id"],
                name="d_category_year_id_sort",
            ),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                condition=models.Q(("is_published", True), ("year__isnull", False)),
                fields=["donor_id", "archive", "year", "id"],
                name="d_archive_year_id_sort",
            ),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                condition=models.Q(("is_published", True), ("year__isnull", False)),
                fields=["donor_id", "category", "archive", "year", "id"],
                name="d_category_archive_year_id_s",
            ),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                condition=models.Q(("is_published", True), ("year__isnull", False)),
                fields=["archive", "year", "id"],
                name="archive_year_id_sort",
            ),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                condition=models.Q(("is_published", True), ("year__isnull", False)),
                fields=["category", "archive", "year", "id"],
                name="category_archive_year_id_sort",
            ),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                condition=models.Q(("is_published", True), ("year__isnull", False)),
                fields=["place_id", "year", "id"],
                name="pyear_id_sort",
            ),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                condition=models.Q(("is_published", True), ("year__isnull", False)),
                fields=["donor_id", "place_id", "year", "id"],
                name="donor_pyear_id_sort",
            ),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                condition=models.Q(("is_published", True), ("year__isnull", False)),
                fields=["donor_id", "category", "place_id", "year", "id"],
                name="d_category_pyear_id_sort",
            ),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                condition=models.Q(("is_published", True), ("year__isnull", False)),
                fields=["donor_id", "archive", "place_id", "year", "id"],
                name="d_archive_pyear_id_sort",
            ),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                condition=models.Q(("is_published", True), ("year__isnull", False)),
                fields=["donor_id", "category", "archive", "place_id", "year", "id"],
                name="d_category_archive_pyear_id_s",
            ),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                condition=models.Q(("is_published", True), ("year__isnull", False)),
                fields=["category", "place_id", "year", "id"],
                name="category_pyear_id_sort",
            ),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                condition=models.Q(("is_published", True), ("year__isnull", False)),
                fields=["archive", "place_id", "year", "id"],
                name="archive_pyear_id_sort",
            ),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                condition=models.Q(("is_published", True), ("year__isnull", False)),
                fields=["category", "archive", "place_id", "year", "id"],
                name="category_archive_pyear_id_sort",
            ),
        ),
    ]
