# Generated by Django 4.2.9 on 2024-02-19 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("kronofoto", "0105_alter_photo_address_alter_photo_city_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaceWordCount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(blank=True, db_index=True, max_length=64)),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kronofoto.place"
                    ),
                ),
            ],
            options={
                "unique_together": {("word", "place")},
            },
        ),
    ]
