# Generated by Django 4.2.9 on 2024-03-15 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("kronofoto", "0109_remove_photo_location_bounds_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_style", models.IntegerField()),
                ("description", models.TextField()),
                ("order", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="PhotoCard",
            fields=[
                (
                    "card_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="kronofoto.card",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="kronofoto.photo"
                    ),
                ),
            ],
            bases=("kronofoto.card",),
        ),
        migrations.CreateModel(
            name="Exhibit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("title", models.CharField(max_length=256)),
                ("description", models.TextField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="kronofoto.photo"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="card",
            name="exhibit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="kronofoto.exhibit"
            ),
        ),
        migrations.CreateModel(
            name="DoublePhotoCard",
            fields=[
                (
                    "photocard_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="kronofoto.photocard",
                    ),
                ),
                (
                    "photo2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="kronofoto.photo"
                    ),
                ),
            ],
            bases=("kronofoto.photocard",),
        ),
    ]
