# Generated by Django 4.2.9 on 2024-03-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kronofoto", "0110_card_photocard_exhibit_card_exhibit_doublephotocard"),
    ]

    operations = [
        migrations.AddField(
            model_name="doublephotocard",
            name="description2",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
