# Generated by Django 4.2.9 on 2024-04-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kronofoto", "0110_photo_modified_key"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                fields=["archive", "id"], name="archive_pho_archive_9df7f8_idx"
            ),
        ),
    ]
