# Generated by Django 4.2.13 on 2024-10-16 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0115_rename_archive_arc_archive_311fbb_idx_kronofoto_a_archive_974281_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FollowArchiveRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_body', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='archive',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.CreateModel(
            name='RemoteActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.URLField(unique=True)),
                ('actor_follows_app', models.BooleanField()),
                ('app_follows_actor', models.BooleanField()),
                ('follow_app_request', models.JSONField(null=True)),
                ('archives_followed', models.ManyToManyField(to='kronofoto.archive')),
                ('requested_archive_follows', models.ManyToManyField(related_name='%(app_label)s_%(class)s_request_follows', through='kronofoto.FollowArchiveRequest', to='kronofoto.archive')),
            ],
        ),
        migrations.AddField(
            model_name='followarchiverequest',
            name='archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kronofoto.archive'),
        ),
        migrations.AddField(
            model_name='followarchiverequest',
            name='remote_actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kronofoto.remoteactor'),
        ),
        migrations.AddField(
            model_name='archive',
            name='archivebase_ptr',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kronofoto.archivebase'),
        ),
        migrations.AddConstraint(
            model_name='followarchiverequest',
            constraint=models.UniqueConstraint(fields=('archive', 'remote_actor'), name='unique_actor_archive_follows'),
        ),
    ]
