# Generated by Django 4.2.13 on 2024-10-24 22:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0115_rename_archive_arc_archive_311fbb_idx_kronofoto_a_archive_974281_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoSphereInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('yaw', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=-180), django.core.validators.MaxValueValidator(limit_value=180)])),
                ('pitch', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=-90), django.core.validators.MaxValueValidator(limit_value=90)])),
                ('photosphere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kronofoto.photosphere')),
            ],
        ),
    ]
