# Generated by Django 4.2.9 on 2024-06-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kronofoto", "0116_figure_card_title_photocard_alignment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="figure",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
