# Generated by Django 4.2.13 on 2024-11-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0116_photosphereinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainstreetset',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
