# Generated by Django 4.2.13 on 2024-10-16 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0117_copytofromarchivebase'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='archive',
            name='archive_slug_idx',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='name',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='slug',
        ),
        migrations.AlterField(
            model_name='archive',
            name='archivebase_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kronofoto.archivebase'),
        ),
        migrations.AlterField(
            model_name='archiveagreement',
            name='archive',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kronofoto.archive', to_field='archivebase_ptr'),
        ),
        migrations.AlterField(
            model_name='archivebase',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='archivebase',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='archivegrouppermission',
            name='archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kronofoto.archive', to_field='archivebase_ptr'),
        ),
        migrations.AlterField(
            model_name='archiveuserpermission',
            name='archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kronofoto.archive', to_field='archivebase_ptr'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kronofoto.archive', to_field='archivebase_ptr'),
        ),
        migrations.AlterField(
            model_name='followarchiverequest',
            name='archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kronofoto.archive', to_field='archivebase_ptr'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kronofoto.archive', to_field='archivebase_ptr'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kronofoto.archive', to_field='archivebase_ptr'),
        ),
        migrations.AlterField(
            model_name='validcategory',
            name='archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kronofoto.archive', to_field='archivebase_ptr'),
        ),
        migrations.AddIndex(
            model_name='archivebase',
            index=models.Index(fields=['slug'], name='archivebase_slug_idx'),
        ),
        migrations.AlterModelTable(
            name='archive',
            table=None,
        ),
    ]
