# Generated by Django 4.2.9 on 2024-08-15 20:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "kronofoto",
            "0115_rename_archive_arc_archive_311fbb_idx_kronofoto_a_archive_974281_idx_and_more",
        ),
        ("kronofoto", "0118_alter_card_card_style"),
    ]

    operations = []
