# Generated by Django 4.2.13 on 2024-10-16 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0119_remove_remoteactor_archives_followed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='id',
        ),
        migrations.AlterField(
            model_name='archive',
            name='archivebase_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kronofoto.archivebase'),
        ),
        migrations.AlterField(
            model_name='archiveagreement',
            name='archive',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kronofoto.archive'),
        ),
        migrations.AlterField(
            model_name='archivegrouppermission',
            name='archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kronofoto.archive'),
        ),
        migrations.AlterField(
            model_name='archiveuserpermission',
            name='archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kronofoto.archive'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kronofoto.archive'),
        ),
        migrations.AlterField(
            model_name='followarchiverequest',
            name='archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kronofoto.archive'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kronofoto.archive'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kronofoto.archive'),
        ),
        migrations.AlterField(
            model_name='validcategory',
            name='archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kronofoto.archive'),
        ),
    ]
