# Generated by Django 4.2.13 on 2024-10-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0120_remove_archive_id_alter_archive_archivebase_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteactor',
            name='archives_followed',
            field=models.ManyToManyField(to='kronofoto.archive'),
        ),
        migrations.AddField(
            model_name='remoteactor',
            name='requested_archive_follows',
            field=models.ManyToManyField(related_name='%(app_label)s_%(class)s_request_follows', through='kronofoto.FollowArchiveRequest', to='kronofoto.archive'),
        ),
    ]
