# Generated by Django 4.2.13 on 2024-10-17 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0121_remoteactor_archives_followed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteArchive',
            fields=[
                ('archivebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kronofoto.archivebase')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kronofoto.remoteactor')),
            ],
            bases=('kronofoto.archivebase',),
        ),
    ]
