# Generated by Django 4.2.13 on 2024-10-17 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0123_alter_exhibit_description_alter_exhibit_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kronofoto.photo'),
        ),
        migrations.AlterField(
            model_name='photocard',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kronofoto.photo'),
        ),
    ]
