# Generated by Django 4.2.13 on 2024-11-08 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0117_mainstreetset_description'),
        ('kronofoto', '0124_alter_figure_photo_alter_photocard_photo'),
    ]

    operations = [
    ]
