# Generated by Django 4.2.13 on 2024-11-12 21:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0125_merge_20241108_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photospherepair',
            name='distance',
            field=models.FloatField(default=500, validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=3000)]),
        ),
    ]
