# Generated by Django 4.2.13 on 2024-11-09 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0122_remotearchive'),
        ('kronofoto', '0125_merge_20241108_1942'),
    ]

    operations = [
    ]
