# Generated by Django 4.2.13 on 2024-12-03 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('kronofoto', '0126_alter_photospherepair_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowArchiveRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_body', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='LdId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ld_id', models.URLField(unique=True)),
                ('object_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OutboxActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.JSONField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RemoteActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.URLField(unique=True)),
                ('actor_follows_app', models.BooleanField(default=False)),
                ('app_follows_actor', models.BooleanField(default=False)),
                ('follow_app_request', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialized_public_key', models.BinaryField(blank=True, null=True)),
                ('encrypted_private_key', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='archive',
            new_name='archivebase_slug_idx',
            old_name='archive_slug_idx',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='location_from_google',
        ),
        migrations.AddField(
            model_name='archive',
            name='encrypted_private_key',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='serialized_public_key',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='server_domain',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='archive',
            name='type',
            field=models.IntegerField(choices=[(0, 'Local'), (1, 'Remote')], default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='remote_image',
            field=models.URLField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='cms_root',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='archive',
            unique_together={('slug', 'server_domain')},
        ),
        migrations.AddField(
            model_name='remoteactor',
            name='archives_followed',
            field=models.ManyToManyField(to='kronofoto.archive'),
        ),
        migrations.AddField(
            model_name='remoteactor',
            name='requested_archive_follows',
            field=models.ManyToManyField(related_name='%(app_label)s_%(class)s_request_follows', through='kronofoto.FollowArchiveRequest', to='kronofoto.archive'),
        ),
        migrations.AddField(
            model_name='ldid',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='followarchiverequest',
            name='archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kronofoto.archive'),
        ),
        migrations.AddField(
            model_name='followarchiverequest',
            name='remote_actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kronofoto.remoteactor'),
        ),
        migrations.AddField(
            model_name='archive',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kronofoto.remoteactor'),
        ),
        migrations.AddConstraint(
            model_name='ldid',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id'), name='unique_content_id_per_object'),
        ),
        migrations.AddConstraint(
            model_name='followarchiverequest',
            constraint=models.UniqueConstraint(fields=('archive', 'remote_actor'), name='unique_actor_archive_follows'),
        ),
    ]
