# Generated by Django 4.2.13 on 2024-11-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0126_alter_photospherepair_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='smalltext',
            field=models.TextField(blank=True, default=''),
        ),
    ]
