# Generated by Django 4.2.13 on 2024-11-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0126_merge_0122_remotearchive_0125_merge_20241108_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.JSONField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='remoteactor',
            name='actor_follows_app',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='remoteactor',
            name='app_follows_actor',
            field=models.BooleanField(default=False),
        ),
    ]
