# Generated by Django 4.2.13 on 2024-11-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0127_outboxactivity_alter_remoteactor_actor_follows_app_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='encrypted_private_key',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='serialized_public_key',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
