# Generated by Django 4.2.13 on 2024-11-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0127_card_smalltext'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='smalltext',
            field=models.TextField(blank=True, default=''),
        ),
    ]
