# Generated by Django 4.2.13 on 2024-12-03 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0128_exhibit_smalltext'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.IntegerField(choices=[(0, 'Text Only'), (1, 'Full'), (2, 'Left'), (3, 'Right')], default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='fill_style_move',
            field=models.IntegerField(choices=[(1, 'Contain'), (2, 'Cover')], default=1),
        ),
        migrations.AddField(
            model_name='card',
            name='photo_move',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kronofoto.photo'),
        ),
    ]
