# Generated by Django 4.2.13 on 2024-11-11 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0128_archive_encrypted_private_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorDataBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kronofoto.donor')),
            ],
        ),
        migrations.CreateModel(
            name='LocalDonorData',
            fields=[
                ('donordatabase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kronofoto.donordatabase')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('home_phone', models.CharField(blank=True, max_length=256)),
                ('street1', models.CharField(blank=True, max_length=256)),
                ('street2', models.CharField(blank=True, max_length=256)),
                ('city', models.CharField(blank=True, max_length=256)),
                ('state', models.CharField(blank=True, max_length=256)),
                ('zip', models.CharField(blank=True, max_length=256)),
                ('country', models.CharField(blank=True, max_length=256)),
            ],
            bases=('kronofoto.donordatabase',),
        ),
        migrations.CreateModel(
            name='RemoteDonorData',
            fields=[
                ('donordatabase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kronofoto.donordatabase')),
                ('ld_id', models.URLField(unique=True)),
            ],
            bases=('kronofoto.donordatabase',),
        ),
    ]
