# Generated by Django 4.2.13 on 2024-12-03 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0130_exhibit_card_to_sparse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotoCard',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='fill_style_move',
            new_name='fill_style',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='photo_move',
            new_name='photo',
        ),
        migrations.CreateModel(
            name='PhotoCard',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('kronofoto.card',),
        ),
    ]
