# Generated by Django 4.2.13 on 2024-11-11 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0130_auto_20241111_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='city',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='country',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='home_phone',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='state',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='street1',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='street2',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='zip',
        ),
    ]
