# Generated by Django 4.2.13 on 2024-11-11 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0131_remove_donor_city_remove_donor_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donordatabase',
            name='donor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kronofoto.donor'),
        ),
    ]
