# Generated by Django 4.2.13 on 2024-11-18 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0126_alter_photospherepair_distance'),
        ('kronofoto', '0132_alter_donordatabase_donor'),
    ]

    operations = [
    ]
