# Generated by Django 4.2.13 on 2024-12-05 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0132_alter_exhibit_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kronofoto.photo'),
        ),
    ]
