# Generated by Django 4.2.13 on 2024-11-18 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0133_merge_20241118_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kronofoto.archivebase'),
        ),
    ]
