# Generated by Django 4.2.13 on 2024-12-20 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0127_followarchiverequest_ldid_outboxactivity_remoteactor_and_more'),
        ('kronofoto', '0133_alter_exhibit_photo'),
    ]

    operations = [
    ]
