# Generated by Django 4.2.13 on 2024-11-24 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('kronofoto', '0134_alter_donor_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='LdId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ld_id', models.URLField(unique=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialized_public_key', models.BinaryField(blank=True, null=True)),
                ('encrypted_private_key', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='RemoteDonorData',
        ),
        migrations.AddConstraint(
            model_name='ldid',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id'), name='unique_content_id_per_object'),
        ),
    ]
