# Generated by Django 4.2.13 on 2024-12-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0134_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='fill_style',
            field=models.IntegerField(choices=[(1, 'Cover'), (2, 'Contain')], default=2),
        ),
    ]
