# Generated by Django 4.2.17 on 2025-02-05 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0134_merge_20241220_0635'),
        ('kronofoto', '0135_alter_card_fill_style'),
    ]

    operations = [
    ]
