# Generated by Django 4.2.17 on 2025-02-24 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0136_photosphere_is_published_alter_photo_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoSphereTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='mainstreetset',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AddField(
            model_name='photosphere',
            name='tour',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kronofoto.photospheretour'),
        ),
    ]
