# Generated by Django 4.2.13 on 2024-11-25 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0136_archivebase_server_domain'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='archivebase',
            unique_together={('slug', 'server_domain')},
        ),
    ]
