# Generated by Django 4.2.13 on 2024-11-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0137_alter_archivebase_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivebase',
            name='slug',
            field=models.SlugField(),
        ),
    ]
