# Generated by Django 4.2.17 on 2025-02-27 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0137_photospheretour_alter_mainstreetset_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photosphere',
            name='tour',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kronofoto.photospheretour'),
        ),
    ]
