# Generated by Django 4.2.17 on 2025-03-11 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0138_alter_photosphere_tour'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourSetDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kronofoto.mainstreetset')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kronofoto.photospheretour')),
            ],
        ),
        migrations.AddField(
            model_name='mainstreetset',
            name='tours',
            field=models.ManyToManyField(through='kronofoto.TourSetDescription', to='kronofoto.mainstreetset'),
        ),
        migrations.AddField(
            model_name='photospheretour',
            name='sets',
            field=models.ManyToManyField(through='kronofoto.TourSetDescription', to='kronofoto.mainstreetset'),
        ),
        migrations.AddIndex(
            model_name='toursetdescription',
            index=models.Index(fields=['tour', 'set'], name='kronofoto_t_tour_id_e0f0fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='toursetdescription',
            constraint=models.UniqueConstraint(fields=('tour', 'set'), name='unique_tour_set'),
        ),
    ]
