# Generated by Django 4.2.17 on 2025-03-25 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0136_merge_20250205_1946'),
        ('kronofoto', '0139_toursetdescription_mainstreetset_tours_and_more'),
    ]

    operations = [
    ]
