# Generated by Django 4.2.13 on 2024-12-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0139_alter_photo_archive_alter_submission_archive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='location_from_google',
        ),
        migrations.AddField(
            model_name='photo',
            name='remote_image',
            field=models.URLField(editable=False, null=True),
        ),
    ]
