# Generated by Django 4.2.17 on 2025-03-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0139_toursetdescription_mainstreetset_tours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photosphere',
            name='use_new_angles',
            field=models.BooleanField(default=False, help_text='This option could fix photo sphere alignment issues. It will be on by default soon.'),
        ),
    ]
