# Generated by Django 4.2.17 on 2025-03-25 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0140_merge_20250325_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followarchiverequest',
            name='request_body',
        ),
        migrations.AddField(
            model_name='followarchiverequest',
            name='request_id',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kronofoto.remoteactor'),
        ),
    ]
