# Generated by Django 4.2.17 on 2025-03-25 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0140_photosphere_use_new_angles'),
        ('kronofoto', '0141_remove_followarchiverequest_request_body_and_more'),
    ]

    operations = [
    ]
