# Generated by Django 4.2.17 on 2025-03-26 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0141_alter_photosphere_use_new_angles'),
        ('kronofoto', '0142_merge_20250325_2239'),
    ]

    operations = [
    ]
