# Generated by Django 4.2.17 on 2025-03-27 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0143_merge_20250326_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kronofoto.remoteactor'),
        ),
    ]
