# Generated by Django 4.2.17 on 2025-03-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0144_alter_place_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowServiceOutbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_actor_profile', models.URLField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='followserviceoutbox',
            constraint=models.UniqueConstraint(fields=('remote_actor_profile',), name='unique_service_follows'),
        ),
    ]
