# Generated by Django 4.2.17 on 2025-03-30 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0145_followserviceoutbox_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.URLField()),
                ('remote_actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kronofoto.remoteactor')),
            ],
        ),
        migrations.AddConstraint(
            model_name='followservicerequest',
            constraint=models.UniqueConstraint(fields=('remote_actor',), name='unique_actor_service_follows'),
        ),
    ]
