# Generated by Django 4.2.17 on 2025-04-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0146_followservicerequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='remote_page',
            field=models.URLField(editable=False, null=True),
        ),
    ]
