# Generated by Django 4.2.20 on 2025-05-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0147_photo_remote_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='max_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='min_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['min_level', 'max_level'], name='kronofoto_p_min_lev_83ac03_idx'),
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('min_level__isnull', True), ('max_level__isnull', True)), ('min_level__lt', models.F('max_level')), _connector='OR'), name='place_zoom_levels_defined'),
        ),
    ]
