# Generated by Django 4.2.20 on 2025-05-15 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0148_place_max_level_place_min_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='actor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='kronofoto.remoteactor'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='server_domain',
            field=models.CharField(blank=True, default='', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='archive',
            name='type',
            field=models.IntegerField(choices=[(0, 'Local'), (1, 'Remote')], default=0, editable=False),
        ),
    ]
