# Generated by Django 4.2.20 on 2025-06-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronofoto', '0149_alter_archive_actor_alter_archive_server_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='license',
            field=models.CharField(choices=[('CC-BY-SA-4.0', 'Attribution-ShareAlike 4.0 International'), ('CC-BY-NC-SA-4.0', 'Attribution-NonCommercial-ShareAlike 4.0 International')], default='CC-BY-SA-4.0', max_length=64),
        ),
        migrations.AddField(
            model_name='submission',
            name='license',
            field=models.CharField(choices=[('CC-BY-SA-4.0', 'Attribution-ShareAlike 4.0 International'), ('CC-BY-NC-SA-4.0', 'Attribution-NonCommercial-ShareAlike 4.0 International')], default='CC-BY-SA-4.0', max_length=64),
        ),
    ]
