# Generated by Django 2.2.7 on 2019-11-18 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('displayed_donors', models.CharField(max_length=512)),
                ('description', models.TextField()),
                ('year_min', models.SmallIntegerField(editable=False, verbose_name='oldest photo year')),
                ('year_max', models.SmallIntegerField(editable=False, verbose_name='newest photo year')),
                ('total_photos', models.SmallIntegerField(editable=False, verbose_name='photos')),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=256)),
                ('first_name', models.CharField(max_length=256)),
                ('home_phone', models.CharField(max_length=256)),
                ('street1', models.CharField(max_length=256)),
                ('street2', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
                ('zip', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_number', models.CharField(max_length=50, unique=True)),
                ('city', models.CharField(max_length=128)),
                ('county', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
                ('year', models.SmallIntegerField()),
                ('caption', models.TextField()),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.Collection')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='donors',
            field=models.ManyToManyField(to='archive.Donor'),
        ),
    ]
