# Generated by Django 2.2.10 on 2020-05-12 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=256)),
                ('first_name', models.CharField(max_length=256)),
                ('home_phone', models.CharField(max_length=256)),
                ('street1', models.CharField(max_length=256)),
                ('street2', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
                ('zip', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('original', models.ImageField(editable=False, null=True, upload_to='')),
                ('h700', models.ImageField(editable=False, null=True, upload_to='')),
                ('thumbnail', models.ImageField(editable=False, null=True, upload_to='')),
                ('photographer', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('county', models.CharField(blank=True, max_length=128)),
                ('state', models.CharField(blank=True, max_length=64)),
                ('country', models.CharField(blank=True, max_length=64, null=True)),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('caption', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.Donor')),
                ('scanner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos_scanned', to='archive.Donor')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScannedPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_photos', to='archive.Donor')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.Donor')),
            ],
        ),
        migrations.CreateModel(
            name='PrePublishPhoto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='archive.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infavor', models.BooleanField()),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', related_query_name='vote', to='archive.ScannedPhoto')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField()),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.Photo')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(blank=True, through='archive.PhotoTag', to='archive.Tag'),
        ),
        migrations.AddField(
            model_name='photo',
            name='terms',
            field=models.ManyToManyField(blank=True, to='archive.Term'),
        ),
        migrations.CreateModel(
            name='CSVRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('donorFirstName', models.TextField()),
                ('donorLastName', models.TextField()),
                ('year', models.IntegerField()),
                ('circa', models.BooleanField()),
                ('scanner', models.TextField()),
                ('photographer', models.TextField()),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('county', models.TextField()),
                ('state', models.TextField()),
                ('country', models.TextField()),
                ('comments', models.TextField()),
                ('added_to_archive', models.DateField()),
                ('photo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('visibility', models.CharField(choices=[('PR', 'Private'), ('UL', 'Unlisted'), ('PU', 'Public')], max_length=2)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('photos', models.ManyToManyField(blank=True, to='archive.Photo')),
            ],
        ),
    ]
