# Generated by Django 2.2.10 on 2020-06-09 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, max_length=64)),
                ('field', models.CharField(choices=[('CA', 'Caption'), ('TA', 'Tag'), ('TE', 'Term')], max_length=2)),
                ('count', models.IntegerField()),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.Photo')),
            ],
        ),
    ]
