# Generated by Django 2.2.7 on 2019-11-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='year_max',
            field=models.SmallIntegerField(editable=False, null=True, verbose_name='newest photo year'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='year_min',
            field=models.SmallIntegerField(editable=False, null=True, verbose_name='oldest photo year'),
        ),
    ]
