# Generated by Django 2.2.7 on 2019-11-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_auto_20191118_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='country',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
