# Generated by Django 2.2.7 on 2019-11-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_auto_20191118_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='year',
            field=models.SmallIntegerField(null=True),
        ),
    ]
