# Generated by Django 2.2.10 on 2020-08-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_phototag_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvrecord',
            name='filename',
            field=models.TextField(unique=True),
        ),
    ]
