# Generated by Django 2.2.7 on 2019-12-05 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_photo_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=256)),
                ('first_name', models.CharField(max_length=256)),
                ('home_phone', models.CharField(max_length=256)),
                ('street1', models.CharField(max_length=256)),
                ('street2', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
                ('zip', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='donor',
            name='city',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='country',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='home_phone',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='state',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='street1',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='street2',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='zip',
        ),
        migrations.CreateModel(
            name='Curator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('contactinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.ContactInfo')),
            ],
        ),
        migrations.AddField(
            model_name='donor',
            name='contactinfo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='archive.ContactInfo'),
            preserve_default=False,
        ),
    ]
