# Generated by Django 2.2.7 on 2019-12-05 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_auto_20191205_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.Curator'),
        ),
    ]
