# Generated by Django 2.2.7 on 2019-12-05 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0008_auto_20191205_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curator',
            name='email',
        ),
        migrations.RemoveField(
            model_name='curator',
            name='username',
        ),
    ]
