# Generated by Django 2.2.7 on 2019-12-09 22:49

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False
    dependencies = [
        ('archive', '0009_auto_20191205_2204'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curator',
            new_name='Contributor',
        ),
    ]
