# Generated by Django 2.2.10 on 2020-10-29 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0009_auto_20201001_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('tag',)},
        ),
    ]
