# Generated by Django 2.2.10 on 2020-10-29 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0010_auto_20201029_2210'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='donor',
            index_together={('last_name', 'first_name')},
        ),
    ]
