# Generated by Django 2.2.10 on 2020-02-17 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0011_needfinalapproval_scannedphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needfinalapproval',
            name='photo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='archive.Photo'),
        ),
    ]
