# Generated by Django 2.2.10 on 2020-02-18 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0012_auto_20200217_2227'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NeedFinalApproval',
            new_name='PrePublishPhoto',
        ),
    ]
