# Generated by Django 2.2.10 on 2021-01-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0012_newcutoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvrecord',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
