# Generated by Django 2.2.10 on 2020-02-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0013_auto_20200218_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepublishphoto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
