# Generated by Django 2.2.10 on 2020-03-04 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0014_auto_20200220_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedphoto',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.Donor'),
        ),
        migrations.AddField(
            model_name='scannedphoto',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
