# Generated by Django 2.2.10 on 2020-03-05 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0015_auto_20200304_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scannedphoto',
            name='donor',
        ),
    ]
