# Generated by Django 2.2.10 on 2020-03-09 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0018_photovote_infavor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photovote',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', related_query_name='vote', to='archive.ScannedPhoto'),
        ),
    ]
