# Generated by Django 2.2.10 on 2020-03-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0021_scannedphoto_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('donorFirstName', models.TextField()),
                ('donorLastName', models.TextField()),
                ('year', models.IntegerField()),
                ('circa', models.BooleanField()),
                ('scanner', models.TextField()),
                ('photographer', models.TextField()),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('county', models.TextField()),
                ('state', models.TextField()),
                ('country', models.TextField()),
                ('comments', models.TextField()),
                ('added_to_archive', models.DateField()),
            ],
        ),
    ]
