# Generated by Django 2.2.10 on 2020-03-19 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0022_csvrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvrecord',
            name='successfully_processed',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.Photo'),
        ),
    ]
