# Generated by Django 2.2.10 on 2020-03-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0023_csvrecord_successfully_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvrecord',
            name='filename',
            field=models.TextField(unique=True),
        ),
    ]
