# Generated by Django 2.2.10 on 2020-03-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0024_auto_20200319_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvrecord',
            name='filename',
            field=models.TextField(),
        ),
    ]
