# Generated by Django 3.2.8 on 2021-12-01 23:30

import archive.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0025_auto_20211006_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoSphere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=archive.models.LowerCaseCharField(editable=False, max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='PhotoSpherePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.photo')),
                ('photosphere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.photosphere')),
            ],
        ),
        migrations.AddField(
            model_name='photosphere',
            name='photos',
            field=models.ManyToManyField(through='archive.PhotoSpherePair', to='archive.Photo'),
        ),
    ]
