# Generated by Django 2.2.10 on 2020-03-19 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0025_auto_20200319_0455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvrecord',
            old_name='successfully_processed',
            new_name='photo',
        ),
    ]
