# Generated by Django 3.2.8 on 2022-06-21 02:57

import archive.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0025_auto_20211006_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='address',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='photo',
            name='year',
            field=models.SmallIntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=1800), django.core.validators.MaxValueValidator(limit_value=2022)]),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=archive.models.LowerCaseCharField(editable=False, max_length=64, unique=True),
        ),
    ]
