# Generated by Django 2.2.10 on 2020-03-19 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0026_auto_20200319_0523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='accession_number',
        ),
    ]
