# Generated by Django 3.2.8 on 2021-12-01 23:33

import archive.models
import archive.storage
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0026_auto_20211201_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='photosphere',
            name='original',
            field=models.ImageField(null=True, storage=archive.storage.OverwriteStorage(), upload_to=archive.models.get_photosphere_path),
        ),
        migrations.AddField(
            model_name='photosphere',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
