# Generated by Django 3.2.8 on 2021-12-01 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0027_auto_20211201_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photospherepair',
            old_name='photo',
            new_name='image',
        ),
    ]
