# Generated by Django 2.2.10 on 2020-03-20 04:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0027_remove_photo_accession_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='h700',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='photo',
            name='original',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='photo',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
