# Generated by Django 3.2.8 on 2021-12-01 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0028_rename_photo_photospherepair_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photosphere',
            old_name='original',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='photospherepair',
            old_name='image',
            new_name='photo',
        ),
    ]
