# Generated by Django 3.2.8 on 2022-06-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0028_geocodecache_squashed_0030_rename_geocodecache_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='location_from_google',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
