# Generated by Django 2.2.10 on 2020-03-24 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archive', '0029_auto_20200324_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='acceptedtags',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='proposedtags',
        ),
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(to='archive.Tag'),
        ),
        migrations.CreateModel(
            name='ProposedTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=64, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
