# Generated by Django 3.2.8 on 2021-12-01 23:35

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0029_auto_20211201_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='photosphere',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
