# Generated by Django 2.2.10 on 2020-03-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0030_auto_20200324_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='terms',
            field=models.ManyToManyField(to='archive.Term'),
        ),
    ]
