# Generated by Django 3.2.14 on 2022-07-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0031_auto_20220630_2230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['term']},
        ),
        migrations.AddField(
            model_name='photosphere',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
