# Generated by Django 3.2.8 on 2021-12-16 23:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0031_auto_20211216_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='photosphere',
            name='name',
            field=models.CharField(default='blank', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photosphere',
            name='heading',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=360)]),
        ),
    ]
