# Generated by Django 2.2.10 on 2020-04-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0032_auto_20200325_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='created_by',
        ),
        migrations.AddField(
            model_name='photo',
            name='proposed_tags',
            field=models.ManyToManyField(blank=True, related_name='proposed_tags', to='archive.Tag'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(blank=True, to='archive.Tag'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='terms',
            field=models.ManyToManyField(blank=True, to='archive.Term'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
