# Generated by Django 3.2.8 on 2022-02-15 23:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0032_auto_20211216_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='year',
            field=models.SmallIntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=1800), django.core.validators.MaxValueValidator(limit_value=2022)]),
        ),
        migrations.AlterField(
            model_name='photosphere',
            name='heading',
            field=models.FloatField(default=0, help_text='Upload an image then edit again to use the interactive tool', validators=[django.core.validators.MinValueValidator(limit_value=-180), django.core.validators.MaxValueValidator(limit_value=180)]),
        ),
        migrations.AlterField(
            model_name='photospherepair',
            name='azimuth',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=-180), django.core.validators.MaxValueValidator(limit_value=180)]),
        ),
        migrations.AlterField(
            model_name='photospherepair',
            name='distance',
            field=models.FloatField(default=500, validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=2000)]),
        ),
        migrations.AlterField(
            model_name='photospherepair',
            name='inclination',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=-90), django.core.validators.MaxValueValidator(limit_value=90)]),
        ),
        migrations.AlterField(
            model_name='photospherepair',
            name='photo',
            field=models.ForeignKey(help_text='Select a photo and photo sphere then click Save and Continue Editing to use the interactive tool', on_delete=django.db.models.deletion.CASCADE, to='archive.photo'),
        ),
        migrations.AlterField(
            model_name='photospherepair',
            name='photosphere',
            field=models.ForeignKey(help_text='Select a photo and photo sphere then click Save and Continue Editing to use the interactive tool', on_delete=django.db.models.deletion.CASCADE, to='archive.photosphere'),
        ),
    ]
