# Generated by Django 3.2.15 on 2022-08-15 20:09

import archive.models.tag
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0033_rename_name_photosphere_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=archive.models.tag.LowerCaseCharField(max_length=64, unique=True),
        ),
    ]
