# Generated by Django 3.2.15 on 2022-11-17 23:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('archive', '0035_photo_local_context_id'), ('archive', '0036_alter_photo_local_context_id'), ('archive', '0037_alter_photo_local_context_id')]

    dependencies = [
        ('archive', '0034_alter_tag_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='local_context_id',
            field=models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator(message='This should be blank or 36 alphanumerics with hyphens grouped like this: 8-4-4-4-12', regex='[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}')]),
        ),
    ]
