# Generated by Django 2.2.10 on 2020-04-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0034_auto_20200408_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
