# Generated by Django 2.2.10 on 2020-04-08 21:01

from django.db import migrations
from django.utils.text import slugify

def slugify_tag(apps, schema_editor):
    Tag = apps.get_model('archive', 'Tag')
    for tag in Tag.objects.all():
        tag.slug = slugify(tag.tag)
        tag.save()

class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0035_tag_slug'),
    ]

    operations = [
        migrations.RunPython(slugify_tag)
    ]
