# Generated by Django 2.2.10 on 2020-04-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0037_auto_20200408_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
