# Generated by Django 2.2.10 on 2020-04-08 21:01
from django.db import migrations
from django.utils.text import slugify


def slugify_term(apps, schema_editor):
    Term = apps.get_model('archive', 'Term')
    for term in Term.objects.all():
        term.slug = slugify(term.term)
        term.save()

class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0038_auto_20200409_1951'),
    ]

    operations = [
        migrations.RunPython(slugify_term)
    ]
