# Generated by Django 2.2.10 on 2020-04-11 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0040_auto_20200409_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='archive.Donor'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='caption',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='city',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='photo',
            name='country',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='county',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='photo',
            name='h700',
            field=models.ImageField(editable=False, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='original',
            field=models.ImageField(editable=False, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='state',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(editable=False, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='year',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
