# Generated by Django 3.2.17 on 2023-02-14 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0041_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='archive',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='archive.archive'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='archive',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='archive.archive'),
            preserve_default=False,
        ),
    ]
