# Generated by Django 2.2.10 on 2020-04-11 00:11

from django.db import migrations

def lookup_donor(apps, schema_editor):
    Photo = apps.get_model('archive', 'Photo')
    for photo in Photo.objects.all():
        photo.donor = photo.collection.donors.all()[0]
        photo.save()

class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0041_auto_20200411_0010'),
    ]

    operations = [
        migrations.RunPython(lookup_donor)
    ]
