# Generated by Django 2.2.10 on 2020-04-11 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0042_auto_20200411_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='collection',
        ),
        migrations.AlterField(
            model_name='photo',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.Donor'),
        ),
    ]
