# Generated by Django 3.2.17 on 2023-02-16 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0044_auto_20230216_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.archive'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.archive'),
        ),
    ]
