# Generated by Django 2.2.10 on 2020-04-11 00:26

from django.db import migrations

def lookup_donor(apps, schema_editor):
    ScannedPhoto = apps.get_model('archive', 'ScannedPhoto')
    for photo in ScannedPhoto.objects.all():
        photo.donor = photo.collection.donors.all()[0]
        photo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0044_auto_20200411_0025'),
    ]

    operations = [
        migrations.RunPython(lookup_donor)
    ]
