# Generated by Django 2.2.10 on 2020-04-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0046_auto_20200411_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='donors',
        ),
        migrations.AddField(
            model_name='collection',
            name='photos',
            field=models.ManyToManyField(blank=True, to='archive.Photo'),
        ),
    ]
