# Generated by Django 2.2.10 on 2020-04-16 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0047_auto_20200411_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='description',
        ),
    ]
