# Generated by Django 2.2.10 on 2020-05-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0048_remove_collection_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='created_by',
            new_name='scanner',
        ),
        migrations.AddField(
            model_name='photo',
            name='photographer',
            field=models.TextField(blank=True),
        ),
    ]
