# Generated by Django 2.2.10 on 2020-05-11 21:14

from django.db import migrations

def splitname(name):
    name = name.strip()
    if not name:
        return name
    names = name.split()
    if not len(names):
        return name
    return names[-1], ' '.join(names[:-1])

def fix_photo_from_csvdata(apps, schema_editor):
    Photo = apps.get_model('archive', 'Photo')
    Contributor = apps.get_model('archive', 'Contributor')
    ContactInfo = apps.get_model('archive', 'ContactInfo')
    for p in Photo.objects.filter(csvrecord__isnull=False):
        scanner = splitname(p.csvrecord.scanner)
        photographer = p.csvrecord.photographer.strip()
        contactInfo, _ = ContactInfo.objects.get_or_create(first_name=scanner[1], last_name=scanner[0])
        contributor, _ = Contributor.objects.get_or_create(contactinfo = contactInfo)
        p.scanner = contributor
        p.photographer = photographer
        p.save()



class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0049_auto_20200511_2112'),
    ]

    operations = [
        migrations.RunPython(fix_photo_from_csvdata)
    ]
