# Generated by Django 2.2.10 on 2020-05-11 21:57

from django.db import migrations


def fix_photo_from_csvdata(apps, schema_editor):
    Photo = apps.get_model('archive', 'Photo')
    for p in Photo.objects.filter(csvrecord__isnull=False):
        p.created = p.csvrecord.added_to_archive
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0050_auto_20200511_2114'),
    ]

    operations = [
        migrations.RunPython(fix_photo_from_csvdata)
    ]
