# Generated by Django 3.2.17 on 2023-05-03 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('archive', '0055_auto_20230324_0435'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveUserPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.archive')),
                ('permission', models.ManyToManyField(to='auth.Permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'archive',
                'verbose_name_plural': 'archive permissions',
            },
        ),
        migrations.AddField(
            model_name='archive',
            name='users',
            field=models.ManyToManyField(through='archive.ArchiveUserPermission', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='archiveuserpermission',
            index=models.Index(fields=['archive', 'user'], name='archive_arc_archive_92f7ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='archiveuserpermission',
            constraint=models.UniqueConstraint(fields=('archive', 'user'), name='unique_archive_user'),
        ),
    ]
