# Generated by Django 3.2.21 on 2023-09-14 05:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archive', '0061_auto_20230912_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='users_starred_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
