# Generated by Django 3.2.21 on 2023-09-14 06:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archive', '0064_auto_20230914_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='users_starred_by',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
