# Generated by Django 3.2.21 on 2023-09-14 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0066_auto_20230914_0621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photographer_temp',
            new_name='photographer',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='photographer_temp',
            new_name='photographer',
        ),
    ]
