# Generated by Django 3.2.21 on 2023-09-20 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0071_auto_20230918_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='users_starred_by',
        ),
    ]
