# Generated by Django 3.2.21 on 2023-10-06 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0075_archive_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivegrouppermission',
            options={'verbose_name': 'archive group permission', 'verbose_name_plural': 'archive permissions'},
        ),
        migrations.AlterModelOptions(
            name='archiveuserpermission',
            options={'verbose_name': 'user-archive permissions', 'verbose_name_plural': 'archive permissions'},
        ),
    ]
