# Generated by Django 3.2.21 on 2023-10-13 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0076_auto_20231006_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValidCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.archive')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.category')),
                ('terms', models.ManyToManyField(to='archive.Term')),
            ],
        ),
        migrations.AddField(
            model_name='archive',
            name='categories',
            field=models.ManyToManyField(through='archive.ValidCategory', to='archive.Category'),
        ),
        migrations.AddField(
            model_name='photo',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='archive.category'),
        ),
        migrations.AddField(
            model_name='submission',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='archive.category'),
        ),
        migrations.AddIndex(
            model_name='validcategory',
            index=models.Index(fields=['category', 'archive'], name='archive_val_categor_eb5c7c_idx'),
        ),
        migrations.AddConstraint(
            model_name='validcategory',
            constraint=models.UniqueConstraint(fields=('category', 'archive'), name='unique_category_archive'),
        ),
    ]
