# Generated by Django 3.2.22 on 2023-10-15 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0079_auto_20231013_0456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
