# Generated by Django 3.2.22 on 2023-11-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0081_alter_term_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
