# Generated by Django 3.2.22 on 2023-11-26 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0082_term_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='terms',
            field=models.ManyToManyField(blank=True, to='archive.Term'),
        ),
    ]
