# Generated by Django 3.2.22 on 2023-12-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0088_place_placetype'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['name'], name='archive_pla_name_c28f33_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['place_type', 'name', 'parent'], name='archive_pla_place_t_0a93db_idx'),
        ),
        migrations.AddIndex(
            model_name='placetype',
            index=models.Index(fields=['name'], name='archive_pla_name_aab364_idx'),
        ),
    ]
