# Generated by Django 3.2.22 on 2023-12-18 06:49

import archive.models.photo
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0090_auto_20231213_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizedPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('cropped', models.BooleanField()),
                ('image', models.ImageField(upload_to=archive.models.photo.get_resized_path)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.photo')),
            ],
        ),
        migrations.AddIndex(
            model_name='sizedphoto',
            index=models.Index(fields=['photo', 'width', 'height'], name='archive_siz_photo_i_5267f0_idx'),
        ),
        migrations.AddIndex(
            model_name='sizedphoto',
            index=models.Index(fields=['photo', 'width', 'cropped'], name='archive_siz_photo_i_cc07e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='sizedphoto',
            constraint=models.UniqueConstraint(fields=('photo', 'width', 'height'), name='unique_photo_size'),
        ),
    ]
