# Generated by Django 3.2.22 on 2024-01-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0094_auto_20240103_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='fullname',
            field=models.CharField(default='', max_length=128),
        ),
    ]
