# Generated by Django 3.2.22 on 2024-01-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0095_place_fullname'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['fullname'], name='archive_pla_fullnam_e7ff62_idx'),
        ),
    ]
