# Generated by Django 4.2.9 on 2024-01-11 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0096_place_archive_pla_fullnam_e7ff62_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photographer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_photographed', to='archive.donor'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_place', to='archive.place'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='scanner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_scanned', to='archive.donor'),
        ),
        migrations.AlterField(
            model_name='photosphere',
            name='links',
            field=models.ManyToManyField(blank=True, to='archive.photosphere'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='photographer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_photographed', to='archive.donor'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_place', to='archive.place'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='scanner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_scanned', to='archive.donor'),
        ),
        migrations.AlterField(
            model_name='term',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_terms', to='archive.termgroup'),
        ),
    ]
