# Generated by Django 4.2.9 on 2024-01-22 07:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "archive",
            "0098_rename_donor_last_name_first_name_archive_don_last_na_6dbbb4_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="h700",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="thumbnail",
        ),
    ]
