# Generated by Django 4.2.9 on 2024-02-15 19:21

from django.db import migrations
from django.db.migrations.operations import AddIndex, RemoveIndex
from django.db.models.indexes import Index


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0100_photo_original_height_photo_original_width"),
    ]

    operations = [AddIndex('Place', Index(fields=('tree_id', 'lft', 'rght'), name='tree_nested_set_index'))]
