# Generated by Django 4.2.9 on 2024-02-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0101_mptt_index"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="photo",
            name="archive_pho_year_f1f0b8_idx",
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                condition=models.Q(("is_published", True), ("year__isnull", False)),
                fields=["year", "id"],
                name="year_id_sort",
            ),
        ),
    ]
