# Generated by Django 4.2.9 on 2024-02-15 23:45

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0103_photo_category_year_id_sort"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="place",
            index=models.Index(
                django.db.models.functions.text.Upper("fullname"),
                name="place_icase_fullname",
            ),
        ),
    ]
