# Generated by Django 4.2.9 on 2024-02-20 20:24

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0106_placewordcount"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="place",
            new_name="archive_tree_nested_set_index",
            old_name="tree_nested_set_index",
        ),
        migrations.RenameIndex(
            model_name="place",
            new_name="archive_place_icase_fullname",
            old_name="place_icase_fullname",
        ),
        migrations.AddIndex(
            model_name="place",
            index=models.Index(
                django.db.models.functions.text.Upper("name"),
                models.F("place_type"),
                name="archive_place_icase_name",
            ),
        ),
    ]
