# Generated by Django 4.2.9 on 2024-02-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "archive",
            "0107_rename_tree_nested_set_index_archive_tree_nested_set_index_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="places",
            field=models.ManyToManyField(editable=False, to="archive.place"),
        ),
    ]
