# Generated by Django 4.2.9 on 2024-03-07 02:59

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0108_photo_places"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="location_bounds",
        ),
        migrations.AddField(
            model_name="submission",
            name="location_point",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
