# Generated by Django 4.2.9 on 2024-05-30 21:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0112_card_archive_car_exhibit_75935e_idx"),
        ("archive", "0113_alter_archive_slug"),
    ]

    operations = []
