# Generated by Django 4.2.9 on 2024-07-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0113_alter_archive_slug"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Location",
        ),
        migrations.AlterField(
            model_name="donor",
            name="last_name",
            field=models.CharField(blank=True, max_length=257),
        ),
    ]
