# Generated by Django 4.2.9 on 2024-06-13 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0115_exhibit_collection"),
    ]

    operations = [
        migrations.CreateModel(
            name="Figure",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.AddField(
            model_name="card",
            name="title",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="photocard",
            name="alignment",
            field=models.IntegerField(
                choices=[(1, "Full"), (2, "Left"), (3, "Right")], default=1
            ),
        ),
        migrations.DeleteModel(
            name="DoublePhotoCard",
        ),
        migrations.AddField(
            model_name="figure",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="archive.card"
            ),
        ),
        migrations.AddField(
            model_name="figure",
            name="photo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="archive.photo"
            ),
        ),
    ]
