# Generated by Django 4.2.9 on 2024-06-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0117_figure_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="card_style",
            field=models.IntegerField(default=0),
        ),
    ]
