# Generated by Django 4.2.9 on 2024-08-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0119_merge_20240815_2016"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="card",
            new_name="kronofoto_c_exhibit_992bd5_idx",
            old_name="archive_car_exhibit_75935e_idx",
        ),
        migrations.AlterField(
            model_name="photocard",
            name="alignment",
            field=models.IntegerField(
                choices=[(1, "Contain"), (2, "Left"), (3, "Right"), (4, "Cover")],
                default=1,
            ),
        ),
        migrations.AlterModelTable(
            name="card",
            table="kronofoto_card",
        ),
        migrations.AlterModelTable(
            name="exhibit",
            table="kronofoto_exhibit",
        ),
        migrations.AlterModelTable(
            name="figure",
            table="kronofoto_figure",
        ),
        migrations.AlterModelTable(
            name="photocard",
            table="kronofoto_photocard",
        ),
    ]
