# Generated by Django 4.2.9 on 2024-08-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0121_remove_card_card_style_photocard_fill_style_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibit",
            name="credits",
            field=models.TextField(blank=True),
        ),
    ]
